### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by pharazon** [phzfi/RIC#1]
Image Resizing - when user gets picture id 123, the cache resizes the image to the correct size of the user's device viewport.

**Comment by kmort89** [comment]
It is usually a bad idea to scale the picture to larger size than the original. We should use RE to get a constraint on how to proceed when this is the case. Keep the issue open, until this has been decided.

**Comment by kmort89** [comment]
PO has confirmed that we can for now simply return the original image if the requested size exceeds the original size. Possible cropping will be handled when the cropping task is taken into sprint. A possible workaround for the upscaling is to include padding (white/black/transparent).

@piiroim1 Please modify the image_resize function to conform to these requirements.
