### ISSUE TITLE
Deny upscale returns larger images than requested

### ISSUE THREAD

**Issue by fubla** [phzfi/RIC#53]
When used in e.g. wordpress we have fixed dimensions that need to be complied to. However, when requesting an image size which would cause the image to be upscaled, the deny-upscale behaviour of the server in some cases returns an image whose height or width may exceed the limits set by the web page.

Example: wordpress page requests an image with dimensions 1024 x 1024 px, but the server returns the original with dimensions 1140 x 550. 
NOTE: returned image dimensions should not exceed size of the requested image (1140 > 1024)!

**Comment by LKeronen** [comment]
The issue has been resolved. Dimensions of returned image should no longer exceed the requested image dimensions in any case. In case of the example: server now responses to given request with image dimensions of 1024 x 494 px (mode=fit) and 550 x 550 (mode default). Either of them exceeds requested width nor height. Default mode quite intuitively preserves the requested aspect ratio.
