### ISSUE TITLE
Image magic repository

### ISSUE THREAD

**Issue by kmort89** [phzfi/RIC#8]
ImageMagic is currently imported as:
"github.com/joonazan/imagick/imagick"

The correct package is probably:
gographics/imagick

This way we get the actual upstream version, unless this was specifically forked to freeze the version?

**Comment by joonazan** [comment]
Upstream would be "github.com/gographics/imagick/imagick".
In addition to freezing the version, my fork contains a bugfix that makes imagick compile on 32-bit systems.

**Comment by kmort89** [comment]
Version freezed forks should be hosted under phzfi.

**Comment by fubla** [comment]
Pull request for fix has been issued, named "Import Fix".

**Comment by fubla** [comment]
Issue fixed with merge of branch "import-fix"
